### ISSUE TITLE
Pass in exact Jacobian

### ISSUE THREAD

**Issue by mauro3** [pwl/DASSL.jl#5]
It would be nice if a function could be passed in for the Jacobian instead of hard-coded finite differences.

**Comment by pwl** [comment]
Would you mind taking a look at 22540a7d70c48af80683564d5469ee15f0fb8b4f and testing it?

It allows you to provide your own Jacobian:
```
F(t,y,dy)=(dy+y.^2)
Fy(t,y,dy)=diagm(2y)
Fdy(t,y,dy)=eye(length(y))
tspan=[0.0,1.0]
y0=[1.0,2.0]
(tn,yn,dyn)=DASSL.dasslSolve(F, y0, tspan, Fy = Fy, Fdy = Fdy)
```

In the above notation `Fy=dF/dy`, while `Fdy=dF/dy'` (maybe there is a better naming convention).  You have to define both, `Fy` and `Fdy`, otherwise DASSL will use the numerical approximation anyway (you wouldn't get any speed boost if you provided one without the other, so it's better to default to numerical Jacobian).

**Comment by mauro3** [comment]
This works for me, thanks for the quick fix.  Concerning the interface, maybe follow PETSc (www.mcs.anl.gov/petsc/petsc-current/docs/manual.pdf p.125) and let the user supply a function `jac(t,y,dy,shift)=dF/dy + shift*dF/dy'`.  Then follow `ODE.jl/ode23s` and use the keyword `jacobian`.

If you document this, maybe mention that `Fdy` is equal to the negative mass matrix when the equation is in explicit form: `M(t,y) * dydt = f(t,y)`

**Comment by pwl** [comment]
Yep, you are right about providing `jac=dF/dy+shift*dF/dy'`, it is the most natural form of jacobian for DASSL.  I will follow your suggestion and implement it as `jacobian` and I will remove the support for `Fdy` and `Fy`.

**Comment by mauro3** [comment]
Any chance of updating to `jacobian=dF/dy+shift*dF/dy'` keyword?

**Comment by pwl** [comment]
Sure, I am working on it right now.

**Comment by mauro3** [comment]
Excellent!

**Comment by pwl** [comment]
Ok, `jacobian` keyword is now implemented as you suggested:

```
atol = 1e-10
rtol = 1e-10
h0   = 1e-2*rtol

dof=2
mu = 1e3
eps = 1/mu^2 # rescaled parameter

function fn(t,y)
    # the ode function dydt = f(t,y)
    out = zeros(Float64,dof)
    out[1] = y[2]
    out[2] = ( (1.0 - y[1]^2)*y[2] - y[1]) / eps
    return out
end

function jac(t,y,dy,a)
    # the Jacobian of f
    #
    # Set to nothing if it is not known
    dfdy = zeros(Float64,dof,dof)
    dfdy[1,1] = 0.0
    dfdy[1,2] = 1.0
    dfdy[2,1] = (-2.0 * y[1]*y[2]-1.0)/eps
    dfdy[2,2] = (1.0 - y[1]^2)/eps
    dfdy = dfdy-a*I
    return dfdy
end

# implicit eqs:
fni(t,y,dy)  = fn(t,y)-dy

y0 = [2., 0]
tspan = [0., 2] # integration interval

(tn,yn)=DASSL.dasslSolve(fni, y0, tspan, reltol=atol, abstol=rtol, initstep = h0, jacobian = jac)
```

If you don't sprecify the jacobian the code falls back to finite differences.

**Comment by mauro3** [comment]
Works fine here. Thanks a lot!
